export const homeTranslation = {
  mn: {
    logOutBtn: "Гарах",
    upperText: "Яг одоо номын ертөнцөд юу болж байгааг хараарай",
    signGoogle: "Google-р нэвтрэх",
    signApple: "Apple-р нэвтрэх",
    createAccount: "Бүртгэл үүсгэх",
    alreadyHaveAcc: "Бүртгэлтэй бол",
    logIn: "Нэвтрэх",
    birthdateIsRequired: "Төрсөн өдөр шаардлагатай",
    invalidEmail: "Буруу имэйл байна",
    emailIsRequired: "Имэйл шаардлагатай",
    usernameIsRequired: "Хэрэглэгчийн нэр шаардлагатай",
    name: "Нэр",
    email: "Имэйл",
    birthDate: "Төрсөн өдөр",
    next: "Үргэлжлүүлэх",
    passwordsDoNotMatch: "Нууц үг таарахгүй байна",
    confirmYourPassword: "Нууц үгээ тааруулна уу",
    password: "Нууц үг",
    confirmPassword: "Нууц үгээ давтана уу",
    eitherYourPasswordEmailIsWrongOrThisAccountDoesNotExist:
      "Таны нууц үг, имэйл буруу эсвэл энэ бүртгэл байхгүй байна",
    toGetStartedFirstEnterYourEmailAndPassword:
      "Эхлэхийн тулд эхлээд имэйл болон нууц үгээ оруулна уу",
    passwordIsRequired: "Нууц үг шаардлагатай",
    forgotPassword: "Нууц үгээ мартсан",
  },
  en: {
    logOutBtn: "Log out",
    upperText: "See what's happening in the book world right now",
    signGoogle: "Continue with Google",
    signApple: "Continue with Apple",
    createAccount: "Create account",
    alreadyHaveAcc: "Already have an account",
    logIn: "log in",
    birthdateIsRequired: "Birthdate is required",
    invalidEmail: "Invalid email",
    emailIsRequired: "Email is required",
    usernameIsRequired: "Username is required",
    name: "Name",
    email: "Email",
    birthDate: "Birth Date",
    next: "Next",
    passwordsDoNotMatch: "Passwords do not match",
    confirmYourPassword: "Confirm your password",
    password: "Password",
    confirmPassword: "Confirm Password",
    eitherYourPasswordEmailIsWrongOrThisAccountDoesNotExist:
      "Either your password, email is wrong, Or this account does not exist",
    toGetStartedFirstEnterYourEmailAndPassword:
      "To get started, first enter your email and password",
    passwordIsRequired: "Password is required",
    forgotPassword: "Forgot password",
  },
};
